### ISSUE TITLE
AvX Selection Bug

### ISSUE THREAD

**Issue by FamousTommyZ** [GavinLilly/SchemeTwister#170]
**Describe the bug**
The Avengers vs X-Men scheme requires 6 heroes, 3 from one team, 3 from another. The randomizer only selects 5 heroes and from more than 2 teams.

**To Reproduce**

1. Either randomly or purposefully, select the Avengers vs X-Men Scheme.
2. Generate a game with said scheme,
3. Scroll down to the selected Heroes.
4. Five heroes of various teams will be present.

**Expected behavior**
Avengers vs X-Men requires 6 heroes, 3 from each of two teams. SchemeTwister should generate 3 heroes, from each of two teams.

**Screenshots**

![AvX](https://github.com/user-attachments/assets/579f2f08-02a9-4af8-8675-22c2e5c2792c)

**Comment by GavinLilly** [comment]
Hello @FamousTommyZ 
Thanks for raising this bug. I've found the bug and issued a fix. Just waiting for testing to complete before I push the fix to production
